// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRA96gPNyCprcG_hYDxZp-h2GU2LZzNU',
    appId: '1:411942216932:web:9e4e635b64d2f4dbf7b8f1',
    messagingSenderId: '411942216932',
    projectId: 'travelers-83ef6',
    authDomain: 'travelers-83ef6.firebaseapp.com',
    storageBucket: 'travelers-83ef6.firebasestorage.app',
    databaseURL: 'https://travelers-83ef6-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXtdCn0eFSQoogFOdgMr3fQz4LbyB6CM',
    appId: '1:411942216932:android:8beba5bb89a36785f7b8f1',
    messagingSenderId: '411942216932',
    projectId: 'travelers-83ef6',
    storageBucket: 'travelers-83ef6.appspot.com',
    databaseURL: 'https://travelers-83ef6-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9qahEbzdobtu3ch1kHcKN82YVIWdWkhA',
    appId: '1:411942216932:ios:3b090dd2315d758af7b8f1',
    messagingSenderId: '411942216932',
    projectId: 'travelers-83ef6',
    storageBucket: 'travelers-83ef6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
    databaseURL: 'https://travelers-83ef6-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9qahEbzdobtu3ch1kHcKN82YVIWdWkhA',
    appId: '1:411942216932:ios:3b090dd2315d758af7b8f1',
    messagingSenderId: '411942216932',
    projectId: 'travelers-83ef6',
    storageBucket: 'travelers-83ef6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
    databaseURL: 'https://travelers-83ef6-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRA96gPNyCprcG_hYDxZp-h2GU2LZzNU',
    appId: '1:411942216932:web:8100643b3afdb22df7b8f1',
    messagingSenderId: '411942216932',
    projectId: 'travelers-83ef6',
    authDomain: 'travelers-83ef6.firebaseapp.com',
    storageBucket: 'travelers-83ef6.firebasestorage.app',
    databaseURL: 'https://travelers-83ef6-default-rtdb.firebaseio.com',
  );
}
